play_sequence:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ig_doorbell
    sequence:
      required: false
      example: "Leave it at the door"
      selector:
        text:
    seq_id:
      required: false
      selector:
        number:
          min: 1
          max: 65535
          mode: box
play_audio:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ig_doorbell
    audio_slot:
      required: true
      selector:
        number:
          min: 1
          max: 10
          mode: box
