"""Mutation check for the Phase 0 rules: each mutant undoes ONE rule and the suite must go red.

    python tools/mutants.py          (from the repo root, where `pytest tests` works)

A test suite that always said "green" would pass every negative test; these mutants are the
positive controls. Every anchor must appear EXACTLY once or the run aborts (a replace() on a
missing anchor returns the text unchanged and would report a "surviving" mutant that was never
applied -- the failure CLAUDE.md warns about).
"""
from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = "custom_components/ig_doorbell/"

MUTANTS = [
    ("resolver falls back to DNS", PKG + "net.py",
     "        lan = self._address_map.get(host)\n        if lan is None:\n",
     "        lan = self._address_map.get(host)\n        if lan is None:\n            import socket as _s; _s.getaddrinfo(host, port)\n"),
    ("get_connection_info returns the credential", PKG + "websocket_api.py",
     '            "device_id": device_id,\n            "role": coordinator.role if coordinator is not None else "unknown",\n            "live_timeout_entity"',
     '            "device_id": device_id,\n            "credential": entry_data["credential"],\n            "role": coordinator.role if coordinator is not None else "unknown",\n            "live_timeout_entity"'),
    ("get_connection_info ignores the doorbell's own pairing role and always says admin", PKG + "websocket_api.py",
     '            "role": coordinator.role if coordinator is not None else "unknown",',
     '            "role": "admin",'),
    ("playback URL points the browser at the doorbell with ?token=", PKG + "media_source.py",
     "        return PlayMedia(signed_video_url(self.hass, device_id, filename), \"video/mp4\")",
     "        return PlayMedia(api.recording_url(device_id, doorbell[CONF_CREDENTIAL], filename), \"video/mp4\")"),
    ("recordings view without auth", PKG + "recordings_view.py",
     "    requires_auth = True", "    requires_auth = False"),
    ("failed pairing is not undone", PKG + "config_flow.py",
     "            undone = await api.async_unpair_app(session, device_id, label)",
     "            undone = False"),
    ("setup skips the TLS check", PKG + "config_flow.py",
     "        await api.async_check_tls(session, found)", "        pass"),
    ("cloud hostname resolved at setup", PKG + "config_flow.py",
     "    if not host or host.lower().rstrip(\".\").endswith(DOORBELL_HOSTNAME_SUFFIX):\n        return None\n",
     "    if not host:\n        return None\n"),
    ("live timeout default changed", PKG + "const.py",
     "LIVE_TIMEOUT_DEFAULT_S = 120", "LIVE_TIMEOUT_DEFAULT_S = 60"),
    ("an entity back to a hard-coded Spanish name", PKG + "lock.py",
     '    _attr_translation_key = "door"\n', '    _attr_name = "Puerta"\n'),
    ("undo by label (404 with spaces on the firmware)", PKG + "api.py",
     'f"{base}/api/unpair_app", data={"slot": str(slots[0])}', 'f"{base}/api/unpair_app", data={"label": label}'),
    ("a language loses an entity name", PKG + "translations/de.json",
     '"name": "Tür"', '"nombre": "Tür"'),
    # --- 1.4.0 (Phase 2): quick replies, REC, the firmware update, In call ---------------------------
    ("the button plays the first quick reply, not the selected one", PKG + "button.py",
     '        seq_id = sel if any(i["id"] == sel for i in items) else items[0]["id"]',
     '        seq_id = items[0]["id"]'),
    ("two quick replies with the same label share one option", PKG + "quick_replies.py",
     """    return {(i["label"] if counts[i["label"]] == 1 else f"{i['label']} ({i['id']})"): i["id"] for i in items}""",
     '    return {i["label"]: i["id"] for i in items}'),
    ("a quick reply name is matched case- and space-sensitively", PKG + "quick_replies.py",
     "    wanted = name.strip().casefold()", "    wanted = name"),
    ("an old firmware's 404 reads as the doorbell's own error", PKG + "api.py",
     "            if resp.status in (404, 405) and not code:", "            if False:"),
    ("the REC switch shows on without the doorbell's own rec", PKG + "switch.py",
     '        return None if rec is None else bool(rec.get("recording"))', "        return None if rec is None else True"),
    ("the REC switch waits for the next poll instead of the doorbell's answer", PKG + "switch.py",
     '            self.coordinator.async_set_updated_data({**(self.coordinator.data or {}), "rec": rec})',
     "            pass"),
    ("REC offered to a user pairing", PKG + "switch.py",
     "        return super().available and self._rec() is not None",
     "        return self.coordinator.last_update_success and self._rec() is not None"),
    ("a firmware check that failed reads as up to date", PKG + "update.py",
     "        return None\n\n    @property\n    def release_summary",
     "        return self.installed_version\n\n    @property\n    def release_summary"),
    ("an install is reported done while the doorbell runs the old version", PKG + "update.py",
     "                if self.installed_version == target:", "                if True:"),
    ("install offered to a user pairing", PKG + "update.py",
     '        if self.coordinator.role == "admin":\n            f |= UpdateEntityFeature.INSTALL',
     "        if True:\n            f |= UpdateEntityFeature.INSTALL"),
    ("a quick reply counts as a conversation", PKG + "call_state.py",
     '            if ev == "call_answered" and d.get("reason") != "quick_reply" and self.supports_in_call:',
     '            if ev == "call_answered" and self.supports_in_call:'),
    ("a poll overrules a fresher webhook", PKG + "call_state.py",
     "        if time.monotonic() - self._in_call_changed < POLL_TRUST_S:\n            return\n", ""),
    ("a lost call_finished is never corrected by the poll", PKG + "call_state.py",
     "        self.in_call = active\n        if active:", "        return\n        if active:"),
    ("the end of an earlier conversation ends this one", PKG + "call_state.py",
     "            if self.in_call_id and call_id and call_id != self.in_call_id:\n                return",
     "            if self.in_call_id and call_id and call_id != self.in_call_id:\n                pass"),
    ("In call offered by a firmware that cannot tell the end", PKG + "binary_sensor.py",
     "        return self._call.supports_in_call", "        return True"),
    ("mode select goes back to the debounced refresh (a 2nd change within 10 s waits)", PKG + "select.py",
     "        self.coordinator.async_set_updated_data({**(self.coordinator.data or {}), **state})",
     "        await self.coordinator.async_request_refresh()"),
    ("mode select accepts a change the doorbell silently dropped", PKG + "select.py",
     "        if not applied:", "        if False:"),
    ("the card is served but never added to the frontend pages (needs a Lovelace resource again)",
     PKG + "card.py", "    add_extra_js_url(hass, url)\n", "    pass\n"),
    ("the card URL loses its cache-busting hash", PKG + "card.py",
     '    url = f"{CARD_URL}?v={digest}"', "    url = CARD_URL"),
    ("the card route tells browsers to keep a month-old copy", PKG + "card.py",
     "StaticPathConfig(CARD_URL, str(CARD_PATH), False)", "StaticPathConfig(CARD_URL, str(CARD_PATH), True)"),
    ("setup no longer registers the card", PKG + "__init__.py",
     "    await async_register_card(hass)\n", ""),
    # --- 1.2.2: the call page in the wall panel's window already on screen (call_page_nav.py) ------
    ("every ring opens a new companion window again", PKG + "notify_ring.py",
     "            if await call_page_nav.async_get(self.hass).async_show(",
     "            if False and await call_page_nav.async_get(self.hass).async_show("),
    ("an acknowledgement from another login counts", PKG + "call_page_nav.py",
     "        if p is None or not _matches(self.hass, p.device_id, user_id, token_id) or p.fut.done():",
     "        if p is None or p.fut.done():"),
    ("a page of another device is asked to navigate", PKG + "call_page_nav.py",
     "    return bool(device_id) and panel_identity.async_get(hass).identify(user_id, token_id) == device_id",
     "    return True"),
    # --- 1.2.3: back to the home page only on a picked wall panel ---------------------------------
    ("every identified companion is treated as a wall panel", PKG + "call_page_nav.py",
     "        if device_id in (entry.options.get(CONF_NOTIFY_PANELS) or []):",
     "        if True:"),
    # --- 1.2.4: the page's companion device (panel_identity.py) -----------------------------------
    ("a user with two companions is resolved by a guess", PKG + "panel_identity.py",
     "        return mine[0] if len(mine) == 1 else None",
     "        return mine[0] if mine else None"),
    ("a browser login counts as a companion", PKG + "panel_identity.py",
     '    return COMPANION_CLIENTS.get(getattr(token, "client_id", None) or "") if token else None',
     '    return "android" if token else None'),
    ("a nonce binds another user's login", PKG + "panel_identity.py",
     '        if reg is None or reg.get("user_id") != user_id:',
     "        if reg is None:"),
    ("a nonce binds a browser login", PKG + "panel_identity.py",
     "        if _token_platform(self.hass, refresh_token_id) != _platform(reg):",
     "        if False:"),
    ("a nonce can be spent twice", PKG + "panel_identity.py",
     "        self.nonces.pop(nonce, None)" + chr(10) + "        if self.bound",
     "        if self.bound"),
    ("a nonce never expires", PKG + "panel_identity.py",
     "        if held is None or held[1] <= time.monotonic():",
     "        if held is None:"),
    ("the exact identity is ignored", PKG + "panel_identity.py",
     "        device_id = self.bound.get(refresh_token_id)",
     "        device_id = None"),
    ("URLs to a panel lose the identifying nonce", PKG + "notify_ring.py",
     '        if target.role != "panel" or not target.device_id:',
     "        if True:"),
    ("get_connection_info ignores the nonce", PKG + "websocket_api.py",
     '        panel_identity.async_get(hass).bind(msg["panel_nonce"][:64], user_id, token_id)',
     "        pass"),
    ("get_connection_info never tells the panel to go home", PKG + "websocket_api.py",
     '            "back_home": back_home,', '            "back_home": False,'),
    # --- 1.4.4: remote viewing - TURN for the card's media (turn_cloud.py) ----------------------------
    ("the pairing credential travels in the TURN URL", PKG + "turn_cloud.py",
     '    url = f"{RELAY_BASE}/device/{device_id.lower()}/app_turn_credentials"',
     '    url = f"{RELAY_BASE}/device/{device_id.lower()}/app_turn_credentials?token={credential}"'),
    ("the browser gets the pairing credential with the TURN list", PKG + "websocket_api.py",
     '    connection.send_result(msg["id"], {"ice_servers": servers, "source": source})',
     '    connection.send_result(msg["id"], {"ice_servers": servers, "source": source, "credential": entry_data[CONF_CREDENTIAL]})'),
    ("a VPS failure is paid again on every card retry", PKG + "turn_cloud.py",
     "    if st.failed_at and now - st.failed_at < FAILURE_BACKOFF_S:",
     "    if False:"),
    ("the card waits for a slow VPS as long as it takes", PKG + "turn_cloud.py",
     "        await asyncio.wait_for(asyncio.shield(st.task), FETCH_DEADLINE_S)",
     "        await st.task"),
    ("fresh TURN credentials are fetched again every time", PKG + "turn_cloud.py",
     "    if st.ice_servers and now - st.fetched_at < CACHE_S:\n        return st.ice_servers, \"cache\"",
     "    if False:\n        return st.ice_servers, \"cache\""),
    ("a STUN entry is handed the TURN password", PKG + "turn_cloud.py",
     '            out.append({"urls": url})',
     '            out.append({"urls": url, "username": str(user), "credential": str(password)})'),
    # --- 1.2.1: the card is also a Lovelace resource (a stale page HTML imports no card) ----------
    ("the card is never added as a Lovelace resource", PKG + "card.py",
     "    await async_sync_lovelace_resource(hass, url)\n    return url\n", "    return url\n"),
    ("a resource at an old URL is left pointing at the old build", PKG + "card.py",
     '        elif keep.get("url") != url or keep.get("type") != RESOURCE_TYPE:',
     "        elif False:"),
    ("a duplicate card resource is kept", PKG + "card.py",
     "keep, extra = (ours[0], ours[1:]) if ours else (None, [])",
     "keep, extra = (ours[0], []) if ours else (None, [])"),
    ("a resource error takes the integration setup down", PKG + "card.py",
     "    except Exception:  # noqa: BLE001", "    except ZeroDivisionError:  # noqa: BLE001"),
    ("the last doorbell removed leaves the resource behind", PKG + "__init__.py",
     "        await async_sync_lovelace_resource(hass, None)\n", "        pass\n"),
    ("removing one of two doorbells removes the card resource", PKG + "__init__.py",
     "    if not [e for e in hass.config_entries.async_entries(DOMAIN) if e.entry_id != entry.entry_id]:",
     "    if True:"),
    ("the call page is not told the card URL", PKG + "panel.py",
     '"card_url": hass.data.get(DATA_CARD_URL)}', '"card_url": None}'),
    # --- 1.1.0: secure local connection (HTTPS) ------------------------------------------------
    ("the local root loses its name constraints", PKG + "https_certs.py",
     "            .add_extension(constraints, critical=True)\n", ""),
    ("the leaf carries names outside the constraints", PKG + "https_certs.py",
     "        if self.is_constrained():\n            dns_names, ips = constrained_names(dns_names, ips)\n", ""),
    ("SNI always serves the local certificate", PKG + "https_certs.py",
     "        if name and self.public is not None and name.lower() == self.public_name:",
     "        if False:"),
    ("HTTPS starts even when it is off", PKG + "https_manager.py",
     "            if not self.enabled or not self._has_entries():", "            if not self._has_entries():"),
    ("the private key travels with the CSR", PKG + "https_certs.py",
     '    return csr.public_bytes(serialization.Encoding.PEM).decode("ascii")\n',
     '    return csr.public_bytes(serialization.Encoding.PEM).decode("ascii") + _key_pem(key).decode()\n'),
    ("a certificate for another key is accepted from the cloud", PKG + "https_manager.py",
     "                    if not https_certs.public_cert_usable(chain, key, hostname):\n"
     "                        return False\n", ""),
    ("the ha_cert voucher is asked through the shared session", PKG + "https_manager.py",
     '                    doorbell["session"], doorbell["device_id"], doorbell["credential"],\n'
     '                    "ha_cert", ha_key,',
     '                    vps, doorbell["device_id"], doorbell["credential"],\n'
     '                    "ha_cert", ha_key,'),
    ("permanent public-name errors are retried every hour", PKG + "https_manager.py",
     '        if code in https_cloud.PERMANENT or code == "no_doorbell":\n'
     "            self._public_permanent = code\n",
     "        if False:\n            self._public_permanent = code\n"),
    ("a taken port crashes instead of raising a repair", PKG + "https_manager.py",
     '                self.error = "port_in_use"\n', "                raise\n"),
    ("the options flow skips the port check", PKG + "config_flow.py",
     "                errors = await _check_port(self.hass, mgr, port)\n", "                errors = {}\n"),
    ("the install page answers outside the LAN", PKG + "https_views.py",
     "def _from_lan(request: web.Request) -> bool:\n    try:",
     "def _from_lan(request: web.Request) -> bool:\n    return True\n    try:"),
    ("the card is not told where the install page is", PKG + "websocket_api.py",
     '            "install_path": INSTALL_PATH,\n', ""),
    # 1.1.1: HTTPS turned itself off seconds after the first enable on a real Home Assistant.
    ("a stale options form turns HTTPS off", PKG + "config_flow.py",
     "            if mgr.enabled != shown and enabled != mgr.enabled:\n",
     "            if False:\n"),
    ("no retry after a transient public-name failure", PKG + "https_manager.py",
     "                self._retry_unsub = async_call_later(self.hass, delay, self._retry_public)\n",
     "                pass\n"),
    ("weather failures never raise a repair", PKG + "https_manager.py",
     "            and dt_util.utcnow() - self._failing_since < PUBLIC_REPAIR_AFTER\n",
     "            and True\n"),
    ("the manager is visible before it is loaded", PKG + "https_manager.py",
     "    await mgr.async_load()\n    hass.data[DATA_HTTPS] = mgr\n",
     "    hass.data[DATA_HTTPS] = mgr\n    await mgr.async_load()\n"),
    ("the cert call gives up before production Let's Encrypt answers", PKG + "https_cloud.py",
     "_VPS_TIMEOUT = aiohttp.ClientTimeout(total=180)\n",
     "_VPS_TIMEOUT = aiohttp.ClientTimeout(total=30)\n"),
    # --- 1.2.0: ring notifications sent by the integration itself -------------------------------
    ("ring tag loses the call (a late resolution clears the next ring)", PKG + "notify_ring.py",
     '    return f"igd_{device_id}_{call_id}"', '    return f"igd_{device_id}"'),
    ("a resolution does not clear the ring", PKG + "notify_ring.py",
     "                coros.append(self._clear(call, t))", "                pass"),
    ("a second resolution is processed again", PKG + "notify_ring.py",
     "        if call is None or call.outcome is not None:\n            return      # not a call we rang",
     "        if call is None:\n            return      # not a call we rang"),
    ("open door accepted from a stale notification", PKG + "notify_ring.py",
     '        if time.monotonic() - call.started > OPEN_DOOR_WINDOW_S:\n            return "too_late"\n', ""),
    ("open door offered by default", PKG + "notify_ring.py",
     '        if (target.role == "phone" and o.get(CONF_NOTIFY_OPEN_DOOR, False)',
     '        if (target.role == "phone" and o.get(CONF_NOTIFY_OPEN_DOOR, True)'),
    ("iPhone ring no longer critical", PKG + "notify_ring.py",
     '                {"interruption-level": "critical",', '                {"interruption-level": "active",'),
    ("the panel chime notice is never cleared without a resolution", PKG + "notify_ring.py",
     '            await self._each(self._clear(call, t) for t in call.targets if t.role == "panel")' + chr(10),
     ""),
    ("a new ring keeps showing the previous visitor", PKG + "image.py",
     "        self._jpeg = None" + chr(10) + "        self._ring_at = time.monotonic()",
     "        self._ring_at = time.monotonic()"),
    ("a 403 keeps a picture for the ring", PKG + "image.py",
     "            _LOGGER.info(\"The owner turned off the picture in ring notices (call_snap): none\")" + chr(10) + "            jpeg = None",
     "            _LOGGER.info(\"The owner turned off the picture in ring notices (call_snap): none\")" + chr(10) + "            jpeg = b'stale'"),
    ("the picture is captured at every ring even when nobody uses it", PKG + "image.py",
     "        if self._wanted_at_ring():", "        if True:"),
    ("a late request fetches a picture of whoever is there now", PKG + "image.py",
     "                and time.monotonic() - self._ring_at <= LAZY_WINDOW_S):", "                ):"),
    ("snapshot request not marked for=alert (call_snap ignored)", PKG + "api.py",
     'f"?for=alert&token={quote(credential)}")', 'f"?token={quote(credential)}")'),
    ("call page becomes admin-only", PKG + "panel.py",
     "        require_admin=False,", "        require_admin=True,"),
    ("notifications step wipes the other options", PKG + "config_flow.py",
     "            options = dict(self._entry.options)\n            options[CONF_NOTIFY_PHONES]",
     "            options = {}\n            options[CONF_NOTIFY_PHONES]"),
    ("a request timeout escapes as a bare TimeoutError (entry dies if the doorbell is off at boot)",
     PKG + "api.py",
     '    except (aiohttp.ClientError, TimeoutError) as err:' + chr(10) + '        raise DoorbellApiError(f"Could not reach the doorbell to configure it',
     '    except aiohttp.ClientError as err:' + chr(10) + '        raise DoorbellApiError(f"Could not reach the doorbell to configure it'),
    ("missed-call time ignores the doorbell's zone", PKG + "notify_ring.py",
     "        tz = dt_util.get_time_zone(tz_name) if isinstance(tz_name, str) and tz_name else None",
     "        tz = None"),
    ("Android clear / missed-call replacement back to normal priority (held by Doze)", PKG + "notify_ring.py",
     'ANDROID_NOW = {"priority": "high", "ttl": 0}', "ANDROID_NOW = {}"),
    ("call page registered without the lock (2 doorbells: one entry in setup_error)", PKG + "panel.py",
     "    async with lock:" + chr(10) + "        await _async_register_locked(hass)",
     "    await _async_register_locked(hass)"),
    ("a failing call page takes the entry down", PKG + "__init__.py",
     "    try:" + chr(10) + "        await async_register_call_page(hass)" + chr(10) + "    except Exception:",
     "    await async_register_call_page(hass)" + chr(10) + "    if False:" + chr(10) + "     try: pass" + chr(10) + "     except Exception:"),
    ("the missed-call notice drops the picture", PKG + "notify_ring.py",
     "        if img is not None and image_id and img.picture_of(call.call_id):",
     "        if False:"),
    ("a later ring's face shown on an older call's notice", PKG + "image.py",
     "        return self._jpeg is not None and call_id is not None and self.call_id == call_id",
     "        return self._jpeg is not None"),
    ("the ring announces a picture the doorbell refused", PKG + "notify_ring.py",
     "        if image and call.picture:", "        if image and self._has_picture():"),
    ("speakers alone do not enable the ring handling", PKG + "notify_ring.py",
     "                    or o.get(CONF_ANNOUNCE_PLAYERS))", "                    )"),
    ("the chime is not served to the speakers", PKG + "announce.py",
     "        [StaticPathConfig(SOUND_URL, str(SOUND_PATH), True)]", "        [StaticPathConfig(SOUND_URL, str(SOUND_PATH), True)] if False else []"),
    ("Alexa gets our mp3 URL, which an Echo cannot play", PKG + "announce.py",
     "        if entry is not None and entry.platform == ALEXA_PLATFORM and entry.device_id:",
     "        if False:"),
    ("the event entity forgets the call resolutions", PKG + "event.py",
     '    "call_answered", "call_declined", "call_missed",\n', ""),
    # --- 1.3.0: Phase 1 entities (tests/test_phase1_entities.py) ---------------------------------
    ("camera: every viewer gets its own capture (no shared window)", PKG + "camera.py",
     "                and time.monotonic() - self._taken_at < SNAPSHOT_MIN_INTERVAL_S):",
     "                and False):"),
    ("camera: captures while the doorbell rings", PKG + "camera.py",
     "        if self._call_live():\n            if (self.coordinator.data",
     "        if False:\n            if (self.coordinator.data"),
    ("camera: ignores the owner's call_snap during a ring", PKG + "camera.py",
     "            if (self.coordinator.data or {}).get(\"call_snap\", 1) == 0:",
     "            if False:"),
    ("ringing: a late resolution of another call ends this ring", PKG + "call_state.py",
     "            if call_id and self.call_id and call_id != self.call_id:\n                return\n",
     ""),
    ("ringing: an unresolved ring is never asked to the doorbell", PKG + "call_state.py",
     "        self._end(_STATUS_REASONS.get(status.get(\"reason\")), status.get(\"by\"))",
     "        self._end(None, None)"),
    ("lock: a failed open is swallowed", PKG + "lock.py",
     "            raise HomeAssistantError(f\"Could not open the door: {err}\") from err",
     "            pass"),
    ("lock: never relocks", PKG + "lock.py",
     "        self._cancel_relock = async_call_later(self.hass, seconds, self._relocked)",
     "        self._cancel_relock = None"),
    ("lock: the old open button stays in the registry", PKG + "button.py",
     "        reg.async_remove(old)\n", "        pass\n"),
    ("settings: available whatever the pairing's role", PKG + "entity.py",
     "        return super().available and self.coordinator.role == \"admin\"",
     "        return super().available"),
    ("settings: a field the doorbell dropped is not noticed", PKG + "coordinator.py",
     "                if str(got) != str(sent) and not _same_number(got, sent):",
     "                if False:"),
    ("slow sources: read even when no entity wants them", PKG + "coordinator.py",
     "            for name in list(self._wanted):\n                due = self._due.get(name, 0) - 1",
     "            for name in list(SOURCES):\n                due = self._due.get(name, 0) - 1"),
    ("slow sources: an admin-only source asked with a user pairing", PKG + "coordinator.py",
     "        if source.admin and self._role != \"admin\":",
     "        if False:"),
    ("slow sources: the mode's reason waits for its 5-minute turn", PKG + "__init__.py",
     "        if envelope.get(\"ev\") == \"mode_changed\":",
     "        if False:"),
    ("detection: turning a class off writes 1", PKG + "switch.py",
     "        await self.coordinator.async_save_detect({self._field: \"0\"}",
     "        await self.coordinator.async_save_detect({self._field: \"1\"}"),
    ("exposure: the 100 us unit is taken for microseconds", PKG + "number.py",
     "        await self._send(int(round(value * 10)), int(gain), \"the manual exposure\")",
     "        await self._send(int(round(value * 1000)), int(gain), \"the manual exposure\")"),
    ("device name: limited in characters, not bytes", PKG + "text.py",
     "        size = len(name.encode(\"utf-8\"))", "        size = len(name)"),
    ("lock type: home_assistant accepted without an entity", PKG + "select.py",
     "        if self._field == \"door_m\" and number == 1 and not data.get(\"ha_e\"):",
     "        if False:"),
    ("webhook: the doorbell may act on this integration's own lock", PKG + "webhook.py",
     "    if registered is not None and registered.platform == DOMAIN:",
     "    if False:"),
    ("flips: a disabled mic gain becomes enabled by default", PKG + "sensor.py",
     "    _attr_translation_key = \"mic_gain\"\n    _attr_icon = \"mdi:microphone-settings\"\n    _attr_entity_category = EntityCategory.DIAGNOSTIC\n    _attr_entity_registry_enabled_default = False\n",
     "    _attr_translation_key = \"mic_gain\"\n    _attr_icon = \"mdi:microphone-settings\"\n    _attr_entity_category = EntityCategory.DIAGNOSTIC\n"),
    ("camera: features back to a bare int (HA 2026 refuses the entity)", PKG + "camera.py",
     "    _attr_supported_features = CameraEntityFeature(0)", "    _attr_supported_features = 0"),
    ("reboot: pressing it does nothing", PKG + "button.py",
     "            await api.async_reboot(c.session, c.device_id, c.credential)",
     "            pass"),
]


def main() -> int:
    # NEGATIVE CONTROL FIRST: the unmutated suite must be green, or a "killed" mutant proves
    # nothing (on 2026-09-26 a harness error in the first test made all 17 look killed).
    r = subprocess.run([sys.executable, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider"],
                       cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        print("ABORT: the unmutated suite is not green - mutants would be meaningless")
        print(r.stdout[-2000:])
        return 2
    print("unmutated suite: green")
    survivors = []
    for name, file_, anchor, change in MUTANTS:
        with tempfile.TemporaryDirectory() as tmp:
            copy_dir = pathlib.Path(tmp) / "repo"
            shutil.copytree(ROOT, copy_dir, ignore=shutil.ignore_patterns(".git", "__pycache__", "node_modules"))
            target_path = copy_dir / file_
            text_ = target_path.read_text(encoding="utf-8")
            n = text_.count(anchor)
            if n != 1:
                print(f"ABORT: anchor for '{name}' appears {n} times in {file_}")
                return 2
            target_path.write_text(text_.replace(anchor, change), encoding="utf-8")
            r = subprocess.run(
                [sys.executable, "-m", "pytest", "tests", "-q", "-x", "-p", "no:cacheprovider"],
                cwd=copy_dir, capture_output=True, text=True,
            )
            red = r.returncode != 0
            print(f"{'RED   (killed)' if red else 'GREEN (SURVIVED)'}  {name}")
            if not red:
                survivors.append(name)
    print(f"\n{len(MUTANTS) - len(survivors)}/{len(MUTANTS)} mutants killed")
    return 1 if survivors else 0


if __name__ == "__main__":
    sys.exit(main())
